### PR TITLE
Changes start and dev npm scripts

### LINKED ISSUE #14: start with node in deployment
nodemon isn't for deployment. It is a utility that speeds up the development process removing the need for restarting the server everytime we change the code. 
If the server crashes due to a bug in the code, nodemon waits for change in any code. There may also occur any permission issues elsewhere because nodemon is installed inside the nodemodules of the project when deploying elsewhere. (cloud)

So, set npm **start** script to **node** and add a **dev** script to start with **nodemon**. This is a commonly used convention.

### PR DESCRIPTION
**Pull request by j-tesla**
Changes nodemon to development dependency, changed start script to start with node and added dev script to start with nodemon

fixes #14

### CODE REVIEW

**Comment by shrinish123** [comment]
Oh, thanks for your contribution. and also pointing this out.
Just one suggestion I would like to give you that we don't need to add 2 start scripts for development as deployment, add 
only one start script for deployment and for development we will use npm run dev  (the dev script), also now as we will start the server the development with npm run dev please also update the READme . for others. 
By the way thanks a lot for showing interest in this project, All the Best :)

**Comment by j-tesla** [comment]
Hey @shrinish123 , what did you mean by 
> Change directory to **Mumble** $ cd GuessMovie
Mumble?

**Comment by shrinish123** [comment]
Oh sorry that was a typo, I fixed it

**Comment by shrinish123** [comment]
Mumble is my other project presently also in KWOC, you can also  contribute to it

**Comment by j-tesla** [comment]
@shrinish123 is this fine?

**Comment by shrinish123** [comment]
Oh sorry for the delay, I  didn't check GitHub, You can surely start on the next issue.Thanks for your contribution

**Pull request merged**
